// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkMXRcs3p8fijmqBLMffCH4cyJGPTFmMI',
    appId: '1:551307648935:web:4eb22701e99e0202b5a082',
    messagingSenderId: '551307648935',
    projectId: 'aeropuerto-ad30a',
    authDomain: 'aeropuerto-ad30a.firebaseapp.com',
    storageBucket: 'aeropuerto-ad30a.firebasestorage.app',
    measurementId: 'G-CXQG8QLMJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMWG8G2fjRM88TYWhdKXK1oUOirfghIo',
    appId: '1:551307648935:android:4978786f79e107a4b5a082',
    messagingSenderId: '551307648935',
    projectId: 'aeropuerto-ad30a',
    storageBucket: 'aeropuerto-ad30a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXHuG-MlABMtaQSr7fenojj9mhn6tYtM',
    appId: '1:551307648935:ios:96abaaf305cab9a6b5a082',
    messagingSenderId: '551307648935',
    projectId: 'aeropuerto-ad30a',
    storageBucket: 'aeropuerto-ad30a.firebasestorage.app',
    iosBundleId: 'com.aeropuerto.aeropuertoApp',
  );

}